### ISSUE TITLE
Add/setup arm control on Jetson Xavier platform

### ISSUE THREAD

**Issue by lvanasse** [clubcapra/ovis#28]
Right now, the .so files of Kinova are only for x86-64 processor architecture. And Markhor's platform is based on the aarch64 processor architecture. 

But Kinova send us the .so files for the aarch64 platform (Ask Ludo). So the code need to be tested with these files to make sure that we can control the arm on the Jetson platform.

**Comment by pioneer-innovation** [comment]
Hi, I meet the same situation! Did you solve this problem?

**Comment by lvanasse** [comment]
I had to ask Kinova directly, and they responded with this link: https://github.com/Kinovarobotics/Extra_code_examples_Jaco2arm/tree/master/sdk%20compiled%20for%20tx2

I'd advise contacting them if there are other issues.
